// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acceptBtn': string;
  'buttonsHolder': string;
  'content-holder': string;
  'cross': string;
  'header': string;
  'invisible': string;
  'modal': string;
  'modal-container': string;
  'subHeader': string;
  'waiting': string;
}
export const cssExports: CssExports;
export default cssExports;
